import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import TensorBoard
from progressive_exaggeration_models import ExaggerationGan
import argparse
import os
import cv2

from ..models.models import efficientnet

input_shape = (224, 96, 3)  # Shape of input of GAN
# tf.keras.mixed_precision.set_global_policy('mixed_float16')


def make_directory(new_dir):
    """
    Recursively makes directories in new_dir if they don't exist already
    :param new_dir: Directory to be created
    """
    try: os.makedirs(new_dir)
    except: pass


class CustomModelCheckpoint(tf.keras.callbacks.Callback):
    """
    This callback saves the model weights at a defined interval and at the end of training.
    """

    def __init__(self, directory, freq=5, skip_start=True):
        """
        :param directory: Directory where results should be saved
        :param freq: Number of epochs between model saving. If 1, model is saved every epoch
        :param skip_start: Boolean flag. If true, does not save initial weights
        """
        super().__init__()
        if freq < 1:
            raise ValueError("Error: checkpoint frequency must be at least 1")
        self.directory = directory
        self.freq = freq
        self.skip_start = skip_start

    def on_epoch_begin(self, epoch, logs=None):
        """
        Saves model weights at the start of the epoch if enough epochs have elapsed since the last save
        :param epoch: Epoch number. Used to determine when to save weights
        :param logs: Unused, included to avoid bugs with inheritance
        """
        if epoch % self.freq == 0 and not (self.skip_start and epoch == 0):
            # self.model.save_pretrained(os.path.join(self.directory, str(epoch) + '.h5'))
            # save_model(self.model, os.path.join(self.directory, str(epoch) + '.h5'))
            make_directory(os.path.join(self.directory, str(epoch)))
            self.model.save_weights(os.path.join(self.directory, str(epoch), 'model'), save_format='tf')

    def on_train_end(self, logs=None):
        """
        Saves the model weights at the end of training
        :param logs: Unused, included to avoid bugs with inheritance
        """
        # self.model.save_pretrained(os.path.join(self.directory, 'final_model.h5'))
        # save_model(self.model, os.path.join(self.directory, 'final_model.h5'))
        make_directory(os.path.join(self.directory, 'final_model'))
        self.model.save_weights(os.path.join(self.directory, 'final_model', 'model'), save_format='tf')


def normalize(image):
    """
    Normalizes image so it can be used as an input to the model
    :param image: Tensor containing 1 or more images
    :return: Normalized tensor
    """
    return image / 255.  # Pixel value range: [0, 1] (for use with sigmoid generator activation)
    # return image / 127.5 - 1.  # Pixel value range: [-1, 1] (for use with tanh generator activation)


def unnormalize(image):
    """
    Undoes normalization of image so it can be viewed as a png
    :param image: Numpy array containing 1 or more images
    :return: Numpy array with values ranging from
    """
    return (image * 255.).astype(int)  # For input values within [0, 1] (sigmoid generator activation)
    # return ((image + 1.) * 127.5).astype(int)  # For input values within [-1, 1] (tanh generator activation)


def load_image(filename):
    """
    Loads and resizes png image for use in training.
    The pixel values of the loaded image will be in the range [-1, 1].
    This range is used to match the output of the generator, which uses a tanh activation.
    :param filename: Filename of image being loaded
    """
    image_str = tf.io.read_file(filename)
    image_decoded = tf.image.decode_png(image_str, channels=3)
    image = tf.cast(image_decoded, tf.float32)
    return normalize(tf.image.resize(image, input_shape[:-1]))


class GanPredictionCallback(tf.keras.callbacks.Callback):
    """
    This callback makes predictions on a predefined set of images after each epoch.
    It saves images generated by the generator for each class as well as the discriminator's predictions.
    """

    def __init__(self, directory, image_paths, num_classes):
        """
        :param directory: Path to directory where predictions will be stored
        :param image_paths: List of paths to images. Model will generate predictions from these images
        :param num_classes: Int, number of classes. Note that a large number of classes may lead to out of memory error
        """
        super().__init__()
        make_directory(directory)
        self.directory = directory
        self.num_classes = num_classes

        # self.images is a list of tuples containing the filename and a 4D tensor representing the image
        self.images = []
        for path in image_paths:
            filename = os.path.basename(os.path.splitext(path)[0])
            self.images.append((filename, tf.expand_dims(load_image(path), axis=0)))

            # Save original image
            make_directory(os.path.join(self.directory, 'original_images'))
            cv2.imwrite(os.path.join(self.directory, 'original_images', filename + ".png"), cv2.imread(path))

    def on_epoch_end(self, epoch, logs=None):
        """
        Makes predictions at the end of an epoch. Saves generated images as .png files and discriminator
        predictions (on original and generated images) in discriminator_results.txt
        :param epoch: Epoch number
        :param logs: Unused, included to avoid bugs with inheritance
        """
        txt_file_output = []  # List of lines to be written to .txt file at the end
        out_dir = os.path.join(self.directory, str(epoch))  # Directory where outputs for this epoch will be saved
        make_directory(out_dir)
        class_labels = tf.convert_to_tensor(list(range(self.num_classes)))  # Used to generate images for each class
        for path, image in self.images:
            # Generate images for each class and then pass those (and the original) to the discriminator
            fakes = self.model.generator.predict([tf.repeat(image, repeats=[self.num_classes], axis=0), class_labels])[0]
            disc_score_generated = self.model.discriminator.predict(tf.convert_to_tensor(fakes))
            disc_score_original = self.model.discriminator.predict(image)

            # Save generated images and append discriminator scores to txt_file_output
            txt_file_output.append("Discriminator predictions for {}:".format(path))
            txt_file_output.append("Original image prediction: {}".format(disc_score_original[0][0]))
            for i in range(self.num_classes):
                cv2.imwrite(os.path.join(out_dir, "{}_fake_class{}.png".format(path, i)),
                            unnormalize(fakes[i])[:,:,::-1])  # cv2.cvtColor(unnormalize(fakes[i]), cv2.COLOR_RGB2BGR))
                txt_file_output.append("Class {} prediction: {}".format(i, disc_score_generated[i][0]))
            txt_file_output.append("\n")

        # Write to .txt file
        with open(os.path.join(out_dir, "discriminator_results.txt"), "w") as f:
            for line in txt_file_output:
                f.write(line)


def get_mmode_png_paths(mmode_dir):
    """
    Given a directory containing mmode images as .png files, returns a list of all .png  in the directory.
    :param mmode_dir: Directory containing mmode .png images
    :returns: List of string paths to mmode images
    """
    # Get list of mmode images
    mmodes = [os.path.join(mmode_dir, f) for f in os.listdir(mmode_dir) if
              os.path.isfile(os.path.join(mmode_dir, f)) and '.png' in f]
    print("Training with {} mmodes".format(len(mmodes)))
    if len(mmodes) == 0:
        print("No mmodes found. Make sure {} contains the mmodes as .png files".format(mmode_dir))
    return mmodes


def load_pretrained_from_checkpoint(ckpt_dir):
    pretrained = efficientnet(cfg['TRAIN']['PARAMS']['EFFICIENTNET'], (224, 90, 3), None, None)
    pretrained.load_weights(ckpt_dir)
    return pretrained
    # input = tf.keras.layers.Input(input_shape)
    # x = tf.keras.layers.Resizing(90, 224)(input)
    # x = pretrained(x)
    # return tf.keras.Model(input, x, name="Pretrained model")


def train_single(mmode_dir, output_dir, batch_size, epochs, num_classes, ckpt_dir=None):
    """
    Runs a single training run for the GAN.
    :param mmode_dir: String path to folder where input m-mode images are stored
    :param output_dir: String path to folder where outputs will be stored
    :param batch_size: Int, batch size for training
    :param epochs: Int, number of epochs to train GAN
    :param num_classes: Number of classes used when training GAN
    :param ckpt_dir: String, path to directory containing checkpoint of pretrained model being explained
    """
    # Get list of mmode paths
    mmodes = get_mmode_png_paths(mmode_dir)[:300]
    if len(mmodes) == 0:
        print("Not training because no mmodes found in directory provided")
        return

    # Make dataset of real images
    ds = tf.data.Dataset.from_tensor_slices(mmodes)
    ds = ds.shuffle(len(mmodes)).map(load_image).batch(batch_size).prefetch(buffer_size=tf.data.AUTOTUNE)

    # Define callbacks
    num_pred_images = 1  # Number of real images that will be used for prediction callback
    pred_image_paths = mmodes if len(mmodes) < num_pred_images else mmodes[:num_pred_images]
    callbacks = [CustomModelCheckpoint(os.path.join(output_dir, 'models'), 5),
                 GanPredictionCallback(os.path.join(output_dir, 'predictions'), pred_image_paths, num_classes),
                 TensorBoard(log_dir=os.path.join(output_dir, 'tensorboard'), histogram_freq=1, profile_batch='30, 100')]

    # pretrained = load_pretrained_from_checkpoint(ckpt_dir)
    # gan = ExaggerationGan(input_shape, batch_size, pretrained, d_per_g=5)
    gan = ExaggerationGan(input_shape, batch_size, None, d_per_g=5)
    gan.compile(Adam(), Adam())
    gan.fit(ds, epochs=epochs, callbacks=callbacks, verbose=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Train explainability GAN")
    parser.add_argument('mmode_dir', help='Folder where input m-mode images are stored')
    parser.add_argument('output_dir', help='Folder where outputs will be stored')
    parser.add_argument('-b', '--batch_size', type=int, default=4, help='Batch size for training GAN')
    parser.add_argument('-e', '--epochs', type=int, default=200, help='Number of epochs to train GAN')
    args = parser.parse_args()

    train_single(args.mmode_dir, args.output_dir, args.batch_size, args.epochs, 10)



    # for g_lr in [.00001, .0001, .001]:
    #     for d_lr in [.001, .0001, .00001]:
    #         out_dir = os.path.join(args.output_dir, 'glr_{}-dlr_{}'.format(g_lr, d_lr))
    #
    #         ds = tf.data.Dataset.from_tensor_slices(mmodes)
    #         ds = ds.shuffle(len(mmodes)).map(load_image).batch(args.batch_size).prefetch(buffer_size=4)
    #
    #         gan = ExaggerationGan(input_shape, 4, d_per_g=5)
    #         gan.compile(Adam(learning_rate=g_lr, beta_1=0., beta_2=.9), Adam(learning_rate=d_lr, beta_1=0., beta_2=.9))
    #         callbacks = [CustomModelCheckpoint(1, os.path.join(out_dir, 'models')),
    #                      TensorBoard(log_dir=os.path.join(out_dir, 'tensorboard'), histogram_freq=1,
    #                                  profile_batch='30, 100')]
    #         make_directory(os.path.join(out_dir, 'models'))
    #         make_directory(os.path.join(out_dir, 'tensorboard'))
    #         gan.fit(ds, epochs=args.epochs, callbacks=callbacks, verbose=True)
    #
    #         # save_model(gan, os.path.join(out_dir, 'final_gan_model.h5'))
