# Note to dev:
# The following list is of configuration parameters is simply an example list of common parameters.
# Be sure to update the readme as you add and remove parameters to this file

PREPROCESS:
  PARAMS:
    AMOUNT_ONLY: False  # If set to True, the tool exits after querying the database and returning counts
    FLOW: 'No'  # Yes for flow only, No for no flow, and Mixed for videos and flow
    FLOW_CROP_WIDTH: 90  # Width to resize to for flow if cropping used
    CROP: False  # Whether clips are to be cropped to the pleural line or not
    SMOOTHING: False
    SMOOTHING_KERNEL_SIZE: 5  # Integer, kernel size of square smoothing kernel filter - MUST be odd
    M_MODE: True  # Whether to extract M-mode like reconstructions
    SHUFFLE: True # If you want to randomize the videos downloaded
    RANDOM_SEED: 1 # If SHUFFLE=False, this does nothing. Otherwise, this is the seed for shuffling
    SLIDING_PROPORTION: 1
    NO_SLIDING_PROPORTION: 1
    WINDOW: 90 # Mini-clip length
    STRIDE: 1  # 1 = contiguous (METHOD='Contiguous' param overrides this)
    IMG_SIZE: [224, 224]  # (Height, width)

  PATHS:
    UNMASKED_VIDEOS: 'raw_videos/'
    MASKED_VIDEOS: 'masked_videos/'
    CROPPED_VIDEOS: 'cropped_videos/'
    SMOOTHED_VIDEOS: 'smoothed_videos/'
    FLOW_VIDEOS: 'flow_videos/'
    CSVS_OUTPUT: 'csvs/'
    NPZ: 'npzs/'
    FLOW_NPZ: 'flow_npzs/'
    M_MODE_NPZ: 'm_mode_npzs'
    MASKING_TOOL: 'auto_masking_deeper.h5'
    EXTRA_UNMASKED_VIDEOS: 'extra_unmasked_videos/'  # assumed to be negative class only
    EXTRA_MASKED_VIDEOS: 'extra_masked_videos/'
    EXTRA_CROPPED_VIDEOS: 'extra_cropped_videos/'  # assumed to be negative class only
    EXTRA_FLOW_VIDEOS: 'extra_flow_videos/'  # assumed to be negative class only
    EXTRA_NPZ: 'extra_npzs/'  # assumed to be negative class only
    EXTRA_FLOW_NPZ: 'extra_flow_npzs/'  # assumed to be negative class only

TRAIN:
  M_MODE: True
  MIXED_PRECISION: False
  OUTPUT_BIAS: False
  PATIENCE: 20
  MODEL_DEF: 'xception'  # xception_raw, lrcn, threeDCNN, vgg16, inflated_resnet50, i3d, xception
  SAVE_BEST_ONLY: True

  SPLITS:
    RANDOM_SEED: -1  # -1 for unseeded
    TRAIN: 0.85
    VAL: 0.15
    TEST: 0

  PARAMS:
    EPOCHS: 50
    BATCH_SIZE: 32  # MAKE SURE THIS IS SET TO 1 FOR GRADCAM
    SHUFFLE: True
    AUGMENTATION_CHANCE: 0.8
    AUGMENTATION:
      BRIGHTNESS_DELTA: 0.1
      HUE_DELTA: 0.2
      CONTRAST_BOUNDS: [ 0.7, 1.0 ]
      SHIFT_LEFTRIGHT_BOUNDS: [ -0.25, 0.25 ]  # Proportion of width to shift by - originally -0.25 to 0.25
      SHIFT_UPDOWN_BOUNDS: [ -0.0, 0.2 ]  # Proportion of height to shift by - No upwards shift since many areas of interest are near the top - originally 0.0 to 0.2
      ROTATE_RANGE: [ -0.1, 0.1 ]  # Range of possible rotation angles (radians)
      SHEAR_RANGE: [ 0.0, 0.1 ]
      ZOOM_RANGE: [ 1.0, 1.5 ]  # DO NOT use lower bound < 1 --> otherwise might cut out parts of pleural line
      RANDOM_NOISE: [ 0.0, 5.0 ]  # Mean, std of sampling distribution, for pixel values in range [0, 255]
      MEDIAN_FILTER_SIZE: 5
    TEST1:
      LR: 0.000001
      L2_LAMBDA: 0.001
    XCEPTION_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    VGG16:
      LR: 0.0001
      LR_DECAY_VAL: 0.1
      DROPOUT: 0.5
      BLOCKS: 3
      L2_REG: 0.01  # Not currently used
      TRANSFER: False  # Whether to use transfer learning (inflated weights from imagenet training) or not
      LAST_FROZEN: 4  # Only if transfer learning is used - for blocks 1 through 5, use 4, 7, 11, 15, 19
      WEIGHT_INITIALIZER: 'he_normal'  # Only currently used for output head
    RES3D:
      LR: 0.0001
      DROPOUT: 0.5
    INFLATED_RESNET50:
      LR: 0.00001  # Initial learning rate
      LR_DECAY_VAL: 0.1  # Set equal to initial learning rate for no LR decay
      DROPOUT: 0.5
      L2_REG: 0.01  # Regularizer penalty
      TRANSFER: True  # Whether to use transfer learning (inflated weights from imagenet training) or not
      LAST_FROZEN: 63  # Last layer (number) to freeze (NOT 0-indexed) if using transfer learning - 40 for end of stage 1, 63 for middle of stage 2, 86 for end of stage 2
      WEIGHT_INITIALIZER: 'he_normal'  # Weight initialization method for layers (if no transfer learning)
    I3D:
      LR: 0.000005  # Initial learning rate
      LR_DECAY_VAL: 0.1  # Set equal to initial learning rate for no LR decay
      DROPOUT: 0.5
      LAST_FROZEN: 74  # Last layer (number) to freeze (NOT 0-indexed)
      L2_REG: 0.01  # Regularizer penalty
      WEIGHT_INITIALIZER: 'he_normal'  # Weight initialization method for layers (if no transfer learning)
    XCEPTION:  # 2D Xception
      LR: 0.00001
      LR_DECAY_VAL: 0.1
      DROPOUT: 0.5
      BLOCKS: 12  # Integer, in the range [1, 14]
      BLOCKS_FROZEN: 4  # Number of blocks to freeze - MUST be less than or equal to the previous ('BLOCKS')
      L2_REG: 0.01
      TRANSFER: True
      LAST_FROZEN: 0  # WHAT ARE THE BREAKPOINTS?
      WEIGHT_INITIALIZER: 'he_normal'
    INCREASE: False

  PATHS:
    CSVS: 'csvs_split/'
    MODEL_OUT: 'results/models/xception/'
    TENSORBOARD: 'results/logs/fit/'

EXPLAINABILITY:
  OUTPUT_FPS: 30
  PROPORTION: 0.02  # Proportion of dataset (random), specified by path NPZ_DF, to generate heatmaps for

  PATHS:
    NPZ: 'data/npzs/'
    FR_CSVS: 'data/csvs/'
    NPZ_DF: 'csvs_split/train.csv'
    MODEL: 'results/models/inflated_resnet50/'
    FEATURE_HEATMAPS: 'feature_heatmaps/'
