# Note to dev:
# The following list is of configuration parameters is simply an example list of common parameters.
# Be sure to update the readme as you add and remove parameters to this file

PREPROCESS:
  PARAMS:
    AMOUNT_ONLY: False  # If set to True, the tool exits after querying the database and returning counts
    FLOW: 'No'  # Yes for flow only, No for no flow, and Mixed for videos and flow
    SHUFFLE: True # If you want to randomize the videos downloaded
    RANDOM_SEED: 1 # If SHUFFLE=False, this does nothing. Otherwise, this is the seed for shuffling
    SLIDING_PROPORTION: 1
    NO_SLIDING_PROPORTION: 1
    METHOD: 'Contiguous'  # 'Stride' or 'Contiguous'
    WINDOW: 90 # Mini-clip length
    STRIDE: 1  # 1 = contiguous (METHOD='Contiguous' param overrides this)
    IMG_SIZE: [224, 224]

  PATHS:
    UNMASKED_VIDEOS: 'raw_videos/'
    MASKED_VIDEOS: 'masked_videos/'
    FLOW_VIDEOS: 'flow_videos/'
    CSVS_OUTPUT: 'csvs/'
    NPZ: 'npzs/'
    FLOW_NPZ: 'flow_npzs'
    MASKING_TOOL: 'auto_masking_deeper.h5'

TRAIN:
  MIXED_PRECISION: false
  PATIENCE: 5
  MODEL_DEF: 'res3d'  # xception_raw, lrcn, threeDCNN, vgg16_raw
  SAVE_BEST_ONLY: True

  SPLITS:
    TRAIN: 0.7
    VAL: 0.3
    TEST: 0

  PARAMS:
    EPOCHS: 15
    BATCH_SIZE: 2
    SHUFFLE: True
    AUGMENTATION_CHANCE: 0.5
    TEST1:
      LR: 0.000001
      L2_LAMBDA: 0.001
    XCEPTION_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    VGG16_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    RES3D:
      LR: 0.0001
      DROPOUT: 0.5
    INCREASE: True

  PATHS:
    CSVS: 'csvs_split/'
    MODEL_OUT: 'results/models/res3d/'
    RANDOM_SEED: 2  # Why is this in paths
    TENSORBOARD: 'results/logs/fit/'
    FEATURE_HEATMAPS: 'feature_heatmaps/'