# Note to dev:
# The following list is of configuration parameters is simply an example list of common parameters.
# Be sure to update the readme as you add and remove parameters to this file

PREPROCESS:
  PARAMS:
    AMOUNT_ONLY: False  # If set to True, the tool exits after querying the database and returning counts
    FLOW: 'Yes'  # Yes for flow only, No for no flow, and Mixed for videos and flow
    SHUFFLE: True # If you want to randomize the videos downloaded
    RANDOM_SEED: 1 # If SHUFFLE=False, this does nothing. Otherwise, this is the seed for shuffling
    SLIDING_PROPORTION: 1
    NO_SLIDING_PROPORTION: 1
    METHOD: 'Contiguous'  # 'Stride' or 'Contiguous'
    WINDOW: 90 # Mini-clip length
    STRIDE: 1  # 1 = contiguous (METHOD='Contiguous' param overrides this)
    IMG_SIZE: [90, 90]

  PATHS:
    UNMASKED_VIDEOS: 'raw_videos/'
    MASKED_VIDEOS: 'masked_videos/'
    FLOW_VIDEOS: 'flow_videos/'
    CSVS_OUTPUT: 'csvs/'
    NPZ: 'npzs/'
    FLOW_NPZ: 'flow_npzs/'
    MASKING_TOOL: 'auto_masking_deeper.h5'

TRAIN:
  MIXED_PRECISION: False
  OUTPUT_BIAS: True
  PATIENCE: 25
  MODEL_DEF: 'inflated_resnet50'  # xception_raw, lrcn, threeDCNN, vgg16_raw, inflated_resnet50
  SAVE_BEST_ONLY: True

  SPLITS:
    RANDOM_SEED: -1  # -1 for unseeded
    TRAIN: 0.7
    VAL: 0.3
    TEST: 0

  PARAMS:
    EPOCHS: 50
    BATCH_SIZE: 1  # MAKE SURE THIS IS SET TO 1 FOR GRADCAM
    SHUFFLE: True
    AUGMENTATION_CHANCE: 0.8
    AUGMENTATION:
      BRIGHTNESS_DELTA: 0.1
      HUE_DELTA: 0.2
      CONTRAST_BOUNDS: [ 0.7, 1.0 ]
      SHIFT_LEFTRIGHT_BOUNDS: [ -0.1, 0.1 ]  # Proportion of width to shift by - originally -0.25 to 0.25
      SHIFT_UPDOWN_BOUNDS: [ -0.2, 0.2 ]  # Proportion of height to shift by - No upwards shift since many areas of interest are near the top - originally 0.0 to 0.2
      ROTATE_RANGE: [ -1.57, 1.57 ]  # Range of possible rotation angles
      SHEAR_RANGE: [ 0.0, 0.1 ]
      ZOOM_RANGE: [ 1.0, 1.5 ]  # DO NOT use lower bound < 1 --> otherwise might cut out parts of pleural line
    TEST1:
      LR: 0.000001
      L2_LAMBDA: 0.001
    XCEPTION_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    VGG16_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    RES3D:
      LR: 0.0001
      DROPOUT: 0.5
    INFLATED_RESNET50:
      LR: 0.0001  # Initial learning rate
      LR_DECAY_VAL: 0.1  # Set equal to initial learning rate for no LR decay
      DROPOUT: 0.5
      LAST_FROZEN: 74  # Last layer (number) to freeze (NOT 0-indexed)
    INCREASE: False

  PATHS:
    CSVS: 'csvs_split/'
    MODEL_OUT: 'results/models/inflated_resnet50/'
    TENSORBOARD: 'results/logs/fit/'

EXPLAINABILITY:
  OUTPUT_FPS: 30
  PROPORTION: 0.02  # Proportion of dataset (random), specified by path NPZ_DF, to generate heatmaps for

  PATHS:
    NPZ: 'data/npzs/'
    FR_CSVS: 'data/csvs/'
    NPZ_DF: 'csvs_split/train.csv'
    MODEL: 'results/models/inflated_resnet50/'
    FEATURE_HEATMAPS: 'feature_heatmaps/'
