# Note to dev:
# The following list is of configuration parameters is simply an example list of common parameters.
# Be sure to update the readme as you add and remove parameters to this file

PREPROCESS:
  DATABASE:
    USERNAME: 
    PASSWORD: 
    HOST: 
    DATABASE:

  PARAMS:
    JUST_ASKING_AMOUNT: False  # If set to True, the tool exits after querying the database and returning counts
    METHOD: 'Stride'  # 'Stride' or 'Contiguous'
    SLIDING_PROPORTION: 0.0042
    NO_SLIDING_PROPORTION: 0.117
    WINDOW: 25 # Mini-clip length
    STRIDE: 3  # 1 = contiguous (METHOD='Contiguous' param overrides this)
    IMG_SIZE: [128, 128]

  PATHS:
    UNMASKED_VIDEOS: 'raw_videos/'
    MASKED_VIDEOS: 'masked_videos/'
    CSVS_OUTPUT: 'csvs/'
    NPZ: 'npzs'