# Note to dev:
# The following list is of configuration parameters is simply an example list of common parameters.
# Be sure to update the readme as you add and remove parameters to this file

PREPROCESS:
  PARAMS:
    AMOUNT_ONLY: False  # If set to True, the tool exits after querying the database and returning counts
    FLOW: 'No'  # Yes for flow only, No for no flow, and Mixed for videos and flow
    SHUFFLE: True # If you want to randomize the videos downloaded
    RANDOM_SEED: 1 # If SHUFFLE=False, this does nothing. Otherwise, this is the seed for shuffling
    SLIDING_PROPORTION: 1
    NO_SLIDING_PROPORTION: 1
    METHOD: 'Contiguous'  # 'Stride' or 'Contiguous'
    WINDOW: 90 # Mini-clip length
    STRIDE: 1  # 1 = contiguous (METHOD='Contiguous' param overrides this)
    IMG_SIZE: [224, 224]

  PATHS:
    UNMASKED_VIDEOS: 'raw_videos/'
    MASKED_VIDEOS: 'masked_videos/'
    FLOW_VIDEOS: 'flow_videos/'
    CSVS_OUTPUT: 'csvs/'
    NPZ: 'npzs/'
    FLOW_NPZ: 'flow_npzs/'
    MASKING_TOOL: 'auto_masking_deeper.h5'

TRAIN:
  MIXED_PRECISION: False
  OUTPUT_BIAS: True
  PATIENCE: 10
  MODEL_DEF: 'res3d'  # xception_raw, lrcn, threeDCNN, vgg16_raw
  SAVE_BEST_ONLY: True

  SPLITS:
    TRAIN: 0.7
    VAL: 0.3
    TEST: 0

  PARAMS:
    EPOCHS: 50
    BATCH_SIZE: 1  # MAKE SURE THIS IS SET TO 1 FOR GRADCAM
    SHUFFLE: True
    AUGMENTATION_CHANCE: 0.8
    AUGMENTATION:
      BRIGHTNESS_DELTA: 0.1
      HUE_DELTA: 0.2
      CONTRAST_BOUNDS: [ 0.7, 1.0 ]
      SHIFT_LEFTRIGHT_BOUNDS: [ -0.25, 0.25 ]  # Proportion of width to shift by
      SHIFT_UPDOWN_BOUNDS: [ 0.0, 0.2 ]  # Proportion of height to shift by - No upwards shift since many areas of interest are near the top
      ROTATE_RANGE: [ -1.57, 1.57 ]  # Range of possible rotation angles
      SHEAR_RANGE: [ 0.0, 0.1 ]
      ZOOM_RANGE: [ 1.0, 1.5 ]  # DO NOT use lower bound < 1 --> otherwise might cut out parts of pleural line
    TEST1:
      LR: 0.000001
      L2_LAMBDA: 0.001
    XCEPTION_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    VGG16_RAW:
      LR: 0.0001
      DROPOUT: 0.5
    RES3D:
      LR: 0.0001
      DROPOUT: 0.5
    INCREASE: True

  PATHS:
    CSVS: 'csvs_split/'
    MODEL_OUT: 'results/models/res3d/'
    RANDOM_SEED: 6  # Why is this in paths
    TENSORBOARD: 'results/logs/fit/'

EXPLAINABILITY:
  OUTPUT_FPS: 30

  PATHS:
    NPZ: 'data/npzs/'
    FR_CSVS: 'data/csvs/'
    NPZ_DF: 'csvs_split/val.csv'
    MODEL: 'results/models/res3d/'
    FEATURE_HEATMAPS: 'feature_heatmaps/'
