# Note to dev:
# The following list is of configuration parameters is simply an example list of common parameters.
# Be sure to update the readme as you add and remove parameters to this file

PREPROCESS:
  PARAMS:
    AMOUNT_ONLY: False  # If set to True, the tool exits after querying the database and returning counts
    SHUFFLE: True # If you want to randomize the videos downloaded
    RANDOM_SEED: 1 # If SHUFFLE=False, this does nothing. Otherwise, this is the seed for shuffling
    SLIDING_PROPORTION: 1
    NO_SLIDING_PROPORTION: 1
    METHOD: 'Contiguous'  # 'Stride' or 'Contiguous'
    WINDOW: 90 # Mini-clip length
    STRIDE: 1  # 1 = contiguous (METHOD='Contiguous' param overrides this)
    IMG_SIZE: [224, 224]

  PATHS:
    UNMASKED_VIDEOS: 'raw_videos/'
    MASKED_VIDEOS: 'masked_videos/'
    CSVS_OUTPUT: 'csvs/'
    NPZ: 'npzs/'
    MASKING_TOOL: 'auto_masking_deeper.h5'

TRAIN:

  MIXED_PRECISION: false
  MODEL_DEF: 'lrcn'
  SAVE_BEST_ONLY: True

  SPLITS:
    TRAIN: 0.7
    VAL: 0.15
    TEST: 0.15

  PARAMS:
    EPOCHS: 15
    BATCH_SIZE: 1
    SHUFFLE: True
    AUGMENTATION_CHANCE: 0.5
    TEST1:
      LR: 0.000001
      L2_LAMBDA: 0.001
    INCREASE: True

  PATHS:
    CSVS: 'csvs_split/'
    MODEL_OUT: 'models/3dcnn/'
    RANDOM_SEED: 2
    TENSORBOARD: 'logs/fit/'